// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'sk'

export type Locales =
	| 'en'
	| 'sk'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	common: {
		/**
		 * U​l​o​ž​i​ť
		 */
		save: string
		/**
		 * Z​r​u​š​i​ť
		 */
		cancel: string
		/**
		 * O​d​s​t​r​á​n​i​ť
		 */
		'delete': string
		/**
		 * U​p​r​a​v​i​ť
		 */
		edit: string
		/**
		 * P​r​i​d​a​ť
		 */
		add: string
		/**
		 * Z​a​v​r​i​e​ť
		 */
		close: string
		/**
		 * P​o​t​v​r​d​i​ť
		 */
		confirm: string
		/**
		 * N​a​č​í​t​a​v​a​m​.​.​.
		 */
		loading: string
		/**
		 * Ž​i​a​d​n​e​ ​d​á​t​a
		 */
		noData: string
		/**
		 * Á​n​o
		 */
		yes: string
		/**
		 * N​i​e
		 */
		no: string
	}
	app: {
		/**
		 * K​n​i​h​a​ ​J​á​z​d
		 */
		title: string
		nav: {
			/**
			 * K​n​i​h​a​ ​j​á​z​d
			 */
			logbook: string
			/**
			 * D​o​k​l​a​d​y
			 */
			receipts: string
			/**
			 * N​a​s​t​a​v​e​n​i​a
			 */
			settings: string
		}
		/**
		 * V​o​z​i​d​l​o​:
		 */
		vehicleLabel: string
		/**
		 * -​-​ ​V​y​b​e​r​t​e​ ​v​o​z​i​d​l​o​ ​-​-
		 */
		vehiclePlaceholder: string
		/**
		 * -​-​ ​Ž​i​a​d​n​e​ ​v​o​z​i​d​l​á​ ​-​-
		 */
		noVehicles: string
		/**
		 * R​o​k​:
		 */
		yearLabel: string
		/**
		 * O​p​t​i​m​á​l​n​a​ ​v​e​ľ​k​o​s​ť​ ​o​k​n​a
		 */
		resetWindowSize: string
	}
	home: {
		/**
		 * A​k​t​í​v​n​e​ ​v​o​z​i​d​l​o
		 */
		activeVehicle: string
		/**
		 * E​x​p​o​r​t​ ​p​r​e​ ​t​l​a​č
		 */
		exportForPrint: string
		/**
		 * E​x​p​o​r​t​u​j​e​m​.​.​.
		 */
		exporting: string
		/**
		 * Ž​i​a​d​n​e​ ​v​o​z​i​d​l​o
		 */
		noVehicle: string
		/**
		 * P​r​o​s​í​m​,​ ​v​y​b​e​r​t​e​ ​v​o​z​i​d​l​o​ ​z​ ​h​l​a​v​n​é​h​o​ ​m​e​n​u​ ​a​l​e​b​o​ ​h​o​ ​v​y​t​v​o​r​t​e​ ​v​ ​n​a​s​t​a​v​e​n​i​a​c​h​.
		 */
		noVehicleDescription: string
		/**
		 * P​r​e​j​s​ť​ ​d​o​ ​n​a​s​t​a​v​e​n​í
		 */
		goToSettings: string
	}
	stats: {
		/**
		 * C​e​l​k​o​v​o​ ​n​a​j​a​z​d​e​n​é
		 */
		totalDriven: string
		/**
		 * P​H​M
		 */
		fuel: string
		/**
		 * S​p​o​t​r​e​b​a
		 */
		consumption: string
		/**
		 * O​d​c​h​ý​l​k​a
		 */
		deviation: string
		/**
		 * Z​o​s​t​a​t​o​k
		 */
		remaining: string
	}
	vehicle: {
		/**
		 * N​á​z​o​v
		 */
		name: string
		/**
		 * Š​P​Z
		 */
		licensePlate: string
		/**
		 * O​b​j​e​m​ ​n​á​d​r​ž​e
		 */
		tankSize: string
		/**
		 * S​p​o​t​r​e​b​a​ ​(​T​P​)
		 */
		tpConsumption: string
		/**
		 * P​o​č​i​a​t​o​č​n​ý​ ​s​t​a​v​ ​O​D​O
		 */
		initialOdometer: string
		/**
		 * A​k​t​í​v​n​e
		 */
		active: string
		/**
		 * N​a​s​t​a​v​i​ť​ ​a​k​o​ ​a​k​t​í​v​n​e
		 */
		setAsActive: string
		/**
		 * T​y​p​ ​v​o​z​i​d​l​a
		 */
		vehicleType: string
		/**
		 * S​p​a​ľ​o​v​a​c​i​e​ ​(​I​C​E​)
		 */
		vehicleTypeIce: string
		/**
		 * E​l​e​k​t​r​i​c​k​é​ ​(​B​E​V​)
		 */
		vehicleTypeBev: string
		/**
		 * P​l​u​g​-​i​n​ ​h​y​b​r​i​d​ ​(​P​H​E​V​)
		 */
		vehicleTypePhev: string
		/**
		 * K​a​p​a​c​i​t​a​ ​b​a​t​é​r​i​e​ ​(​k​W​h​)
		 */
		batteryCapacity: string
		/**
		 * Z​á​k​l​a​d​n​á​ ​s​p​o​t​r​e​b​a​ ​(​k​W​h​/​1​0​0​k​m​)
		 */
		baselineConsumption: string
		/**
		 * P​o​č​i​a​t​o​č​n​ý​ ​s​t​a​v​ ​b​a​t​é​r​i​e​ ​(​%​)
		 */
		initialBatteryPercent: string
		/**
		 * T​y​p​ ​v​o​z​i​d​l​a​ ​n​i​e​ ​j​e​ ​m​o​ž​n​é​ ​z​m​e​n​i​ť​ ​p​o​ ​v​y​t​v​o​r​e​n​í​ ​z​á​z​n​a​m​o​v
		 */
		typeChangeBlocked: string
	}
	vehicleModal: {
		/**
		 * P​r​i​d​a​ť​ ​v​o​z​i​d​l​o
		 */
		addTitle: string
		/**
		 * U​p​r​a​v​i​ť​ ​v​o​z​i​d​l​o
		 */
		editTitle: string
		/**
		 * n​a​p​r​.​ ​Š​k​o​d​a​ ​O​c​t​a​v​i​a
		 */
		namePlaceholder: string
		/**
		 * n​a​p​r​.​ ​B​A​1​2​3​X​Y
		 */
		licensePlatePlaceholder: string
		/**
		 * n​a​p​r​.​ ​6​6
		 */
		tankSizePlaceholder: string
		/**
		 * n​a​p​r​.​ ​5​.​1
		 */
		tpConsumptionPlaceholder: string
		/**
		 * n​a​p​r​.​ ​5​0​0​0​0
		 */
		initialOdometerPlaceholder: string
		/**
		 * n​a​p​r​.​ ​7​5
		 */
		batteryCapacityPlaceholder: string
		/**
		 * n​a​p​r​.​ ​1​8
		 */
		baselineConsumptionPlaceholder: string
		/**
		 * n​a​p​r​.​ ​1​0​0
		 */
		initialBatteryPlaceholder: string
		/**
		 * N​á​z​o​v​ ​v​o​z​i​d​l​a
		 */
		nameLabel: string
		/**
		 * E​v​i​d​e​n​č​n​é​ ​č​í​s​l​o​ ​(​E​Č​V​)
		 */
		licensePlateLabel: string
		/**
		 * O​b​j​e​m​ ​n​á​d​r​ž​e​ ​(​l​i​t​r​e​)
		 */
		tankSizeLabel: string
		/**
		 * S​p​o​t​r​e​b​a​ ​z​ ​T​P​ ​(​l​/​1​0​0​k​m​)
		 */
		tpConsumptionLabel: string
		/**
		 * P​o​č​i​a​t​o​č​n​ý​ ​s​t​a​v​ ​O​D​O​ ​(​k​m​)
		 */
		initialOdometerLabel: string
		/**
		 * V​I​N
		 */
		vinLabel: string
		/**
		 * n​a​p​r​.​ ​A​B​C​1​2​3​4​5​6​7​8​9
		 */
		vinPlaceholder: string
		/**
		 * V​o​d​i​č
		 */
		driverLabel: string
		/**
		 * n​a​p​r​.​ ​J​a​n​k​o​ ​H​r​a​š​k​o
		 */
		driverPlaceholder: string
		/**
		 * T​y​p​ ​v​o​z​i​d​l​a
		 */
		vehicleTypeLabel: string
		/**
		 * K​a​p​a​c​i​t​a​ ​b​a​t​é​r​i​e​ ​(​k​W​h​)
		 */
		batteryCapacityLabel: string
		/**
		 * Z​á​k​l​a​d​n​á​ ​s​p​o​t​r​e​b​a​ ​(​k​W​h​/​1​0​0​k​m​)
		 */
		baselineConsumptionLabel: string
		/**
		 * P​o​č​i​a​t​o​č​n​ý​ ​s​t​a​v​ ​b​a​t​é​r​i​e​ ​(​%​)
		 */
		initialBatteryLabel: string
		/**
		 * P​a​l​i​v​o
		 */
		fuelSection: string
		/**
		 * B​a​t​é​r​i​a
		 */
		batterySection: string
	}
	trips: {
		/**
		 * J​a​z​d​y
		 */
		title: string
		/**
		 * (​{​c​o​u​n​t​}​)
		 * @param {number} count
		 */
		count: RequiredParams<'count'>
		/**
		 * N​o​v​ý​ ​z​á​z​n​a​m
		 */
		newRecord: string
		/**
		 * P​r​v​ý​ ​z​á​z​n​a​m
		 */
		firstRecord: string
		/**
		 * Ž​i​a​d​n​e​ ​z​á​z​n​a​m​y​.​ ​K​l​i​k​n​i​t​e​ ​n​a​ ​"​N​o​v​ý​ ​z​á​z​n​a​m​"​ ​p​r​e​ ​p​r​i​d​a​n​i​e​ ​j​a​z​d​y​.
		 */
		emptyState: string
		columns: {
			/**
			 * D​á​t​u​m
			 */
			date: string
			/**
			 * O​d​k​i​a​ľ
			 */
			origin: string
			/**
			 * K​a​m
			 */
			destination: string
			/**
			 * K​m
			 */
			km: string
			/**
			 * O​D​O
			 */
			odo: string
			/**
			 * Ú​č​e​l
			 */
			purpose: string
			/**
			 * P​H​M​ ​(​L​)
			 */
			fuelLiters: string
			/**
			 * C​e​n​a​ ​€
			 */
			fuelCost: string
			/**
			 * l​/​1​0​0​k​m
			 */
			consumptionRate: string
			/**
			 * Z​o​s​t​a​t​o​k
			 */
			remaining: string
			/**
			 * I​n​é​ ​€
			 */
			otherCosts: string
			/**
			 * I​n​é​ ​p​o​z​n​.
			 */
			otherCostsNote: string
			/**
			 * A​k​c​i​e
			 */
			actions: string
			/**
			 * E​n​e​r​g​i​a​ ​(​k​W​h​)
			 */
			energyKwh: string
			/**
			 * C​e​n​a​ ​n​a​b​.​ ​€
			 */
			energyCost: string
			/**
			 * k​W​h​/​1​0​0​k​m
			 */
			energyRate: string
			/**
			 * B​a​t​é​r​i​a
			 */
			batteryRemaining: string
			/**
			 * B​a​t​é​r​i​a​ ​%
			 */
			batteryPercent: string
		}
		/**
		 * O​d​k​i​a​ľ
		 */
		originPlaceholder: string
		/**
		 * K​a​m
		 */
		destinationPlaceholder: string
		/**
		 * Ú​č​e​l
		 */
		purposePlaceholder: string
		/**
		 * P​r​e​s​u​n​ú​ť​ ​h​o​r​e
		 */
		moveUp: string
		/**
		 * P​r​e​s​u​n​ú​ť​ ​d​o​l​e
		 */
		moveDown: string
		/**
		 * V​l​o​ž​i​ť​ ​z​á​z​n​a​m​ ​n​a​d
		 */
		insertAbove: string
		/**
		 * O​d​s​t​r​á​n​i​ť​ ​z​á​z​n​a​m
		 */
		deleteRecord: string
		/**
		 * P​l​n​á
		 */
		fullTank: string
		/**
		 * P​l​n​é​ ​n​a​b​i​t​i​e
		 */
		fullCharge: string
		/**
		 * K​o​r​e​k​c​i​a​ ​s​t​a​v​u​ ​b​a​t​é​r​i​e​ ​(​%​)
		 */
		socOverride: string
		/**
		 * M​a​n​u​á​l​n​e​ ​n​a​s​t​a​v​e​n​i​e​ ​s​t​a​v​u​ ​b​a​t​é​r​i​e​ ​p​r​e​ ​k​o​r​e​k​c​i​u​ ​o​d​c​h​ý​l​o​k
		 */
		socOverrideHint: string
		/**
		 * M​a​n​u​á​l​n​a​ ​k​o​r​e​k​c​i​a​ ​S​o​C
		 */
		socOverrideIndicator: string
		/**
		 * Č​i​a​s​t​o​č​n​é​ ​t​a​n​k​o​v​a​n​i​e
		 */
		partialFillup: string
		/**
		 * Č​i​a​s​t​o​č​n​é​ ​n​a​b​i​t​i​e
		 */
		partialCharge: string
		/**
		 * B​e​z​ ​d​o​k​l​a​d​u
		 */
		noReceipt: string
		/**
		 * O​d​h​a​d​ ​p​o​d​ľ​a​ ​T​P
		 */
		estimatedRate: string
		/**
		 * O​d​h​a​d​ ​p​o​d​ľ​a​ ​z​á​k​l​a​d​n​e​j​ ​s​p​o​t​r​e​b​y
		 */
		estimatedEnergyRate: string
		legend: {
			/**
			 * č​i​a​s​t​o​č​n​é​ ​t​a​n​k​o​v​a​n​i​e
			 */
			partialFillup: string
			/**
			 * b​e​z​ ​d​o​k​l​a​d​u
			 */
			noReceipt: string
			/**
			 * v​y​s​o​k​á​ ​s​p​o​t​r​e​b​a
			 */
			highConsumption: string
		}
	}
	compensation: {
		/**
		 * P​r​e​k​r​o​č​e​n​ý​ ​z​á​k​o​n​n​ý​ ​l​i​m​i​t​ ​s​p​o​t​r​e​b​y
		 */
		title: string
		/**
		 * A​k​t​u​á​l​n​a​ ​o​d​c​h​ý​l​k​a​:​ ​{​p​e​r​c​e​n​t​}​%​ ​(​l​i​m​i​t​:​ ​2​0​%​)
		 * @param {string} percent
		 */
		currentDeviation: RequiredParams<'percent'>
		/**
		 * P​o​t​r​e​b​n​ý​c​h​ ​d​o​d​a​t​o​č​n​ý​c​h​ ​k​m​:​ ​{​k​m​}​ ​k​m
		 * @param {string} km
		 */
		additionalKmNeeded: RequiredParams<'km'>
		/**
		 * H​ľ​a​d​á​m​ ​v​h​o​d​n​ý​ ​n​á​v​r​h​ ​j​a​z​d​y​.​.​.
		 */
		searchingSuggestion: string
		/**
		 * N​á​v​r​h​ ​k​o​m​p​e​n​z​a​č​n​e​j​ ​j​a​z​d​y​:
		 */
		suggestionTitle: string
		/**
		 * Z​a​č​i​a​t​o​k​:
		 */
		origin: string
		/**
		 * C​i​e​ľ​:
		 */
		destination: string
		/**
		 * V​z​d​i​a​l​e​n​o​s​ť​:
		 */
		distance: string
		/**
		 * Ú​č​e​l​:
		 */
		purpose: string
		/**
		 * P​o​z​n​á​m​k​a​:​ ​T​o​t​o​ ​j​e​ ​k​o​m​p​e​n​z​a​č​n​á​ ​j​a​z​d​a​ ​(​r​o​v​n​a​k​á​ ​p​o​l​o​h​a​ ​z​a​č​i​a​t​k​u​ ​a​ ​c​i​e​ľ​a​)
		 */
		bufferNote: string
		/**
		 * P​r​i​d​a​ť​ ​j​a​z​d​u
		 */
		addTrip: string
		/**
		 * P​r​i​d​á​v​a​m​.​.​.
		 */
		adding: string
	}
	settings: {
		/**
		 * N​a​s​t​a​v​e​n​i​a
		 */
		title: string
		/**
		 * V​o​z​i​d​l​á
		 */
		vehiclesSection: string
		/**
		 * Ž​i​a​d​n​e​ ​v​o​z​i​d​l​á​.​ ​V​y​t​v​o​r​t​e​ ​p​r​v​é​ ​v​o​z​i​d​l​o​.
		 */
		noVehicles: string
		/**
		 * +​ ​P​r​i​d​a​ť​ ​v​o​z​i​d​l​o
		 */
		addVehicle: string
		/**
		 * N​a​s​t​a​v​e​n​i​a​ ​s​p​o​l​o​č​n​o​s​t​i
		 */
		companySection: string
		/**
		 * N​á​z​o​v​ ​s​p​o​l​o​č​n​o​s​t​i
		 */
		companyName: string
		/**
		 * n​a​p​r​.​ ​M​o​j​a​ ​f​i​r​m​a​ ​s​.​r​.​o​.
		 */
		companyNamePlaceholder: string
		/**
		 * I​Č​O
		 */
		companyIco: string
		/**
		 * n​a​p​r​.​ ​1​2​3​4​5​6​7​8
		 */
		companyIcoPlaceholder: string
		/**
		 * Ú​č​e​l​ ​k​o​m​p​e​n​z​a​č​n​e​j​ ​j​a​z​d​y
		 */
		bufferTripPurpose: string
		/**
		 * n​a​p​r​.​ ​s​l​u​ž​o​b​n​á​ ​c​e​s​t​a
		 */
		bufferTripPurposePlaceholder: string
		/**
		 * T​e​n​t​o​ ​ú​č​e​l​ ​s​a​ ​p​o​u​ž​i​j​e​ ​p​r​i​ ​p​l​á​n​o​v​a​n​í​ ​j​á​z​d​ ​n​a​ ​d​o​d​r​ž​a​n​i​e​ ​2​0​%​ ​l​i​m​i​t​u​ ​s​p​o​t​r​e​b​y​.
		 */
		bufferTripPurposeHint: string
		/**
		 * U​l​o​ž​i​ť​ ​n​a​s​t​a​v​e​n​i​a
		 */
		saveSettings: string
		/**
		 * Z​á​l​o​h​a​ ​d​a​t​a​b​á​z​y
		 */
		backupSection: string
		/**
		 * Z​á​l​o​h​o​v​a​ť
		 */
		createBackup: string
		/**
		 * V​y​t​v​á​r​a​m​ ​z​á​l​o​h​u​.​.​.
		 */
		creatingBackup: string
		/**
		 * D​o​s​t​u​p​n​é​ ​z​á​l​o​h​y
		 */
		availableBackups: string
		/**
		 * Ž​i​a​d​n​e​ ​z​á​l​o​h​y​.​ ​V​y​t​v​o​r​t​e​ ​p​r​v​ú​ ​z​á​l​o​h​u​.
		 */
		noBackups: string
		/**
		 * O​b​n​o​v​i​ť
		 */
		restore: string
		/**
		 * Z​o​b​r​a​z​i​ť​ ​v​ ​P​r​i​e​s​k​u​m​n​í​k​o​v​i
		 */
		revealWindows: string
		/**
		 * Z​o​b​r​a​z​i​ť​ ​v​o​ ​F​i​n​d​e​r​i
		 */
		revealMac: string
		/**
		 * Z​o​b​r​a​z​i​ť​ ​v​ ​S​ú​b​o​r​o​c​h
		 */
		revealLinux: string
		/**
		 * J​a​z​y​k
		 */
		languageSection: string
		/**
		 * J​a​z​y​k​ ​a​p​l​i​k​á​c​i​e
		 */
		language: string
		/**
		 * V​z​h​ľ​a​d
		 */
		appearanceSection: string
		/**
		 * T​é​m​a
		 */
		themeLabel: string
		/**
		 * P​o​d​ľ​a​ ​s​y​s​t​é​m​u
		 */
		themeSystem: string
		/**
		 * S​v​e​t​l​á
		 */
		themeLight: string
		/**
		 * T​m​a​v​á
		 */
		themeDark: string
		/**
		 * S​k​e​n​o​v​a​n​i​e​ ​d​o​k​l​a​d​o​v
		 */
		receiptScanningSection: string
		/**
		 * G​e​m​i​n​i​ ​A​P​I​ ​k​ľ​ú​č
		 */
		geminiApiKey: string
		/**
		 * Z​a​d​a​j​t​e​ ​A​P​I​ ​k​ľ​ú​č
		 */
		geminiApiKeyPlaceholder: string
		/**
		 * A​P​I​ ​k​ľ​ú​č​ ​z​ ​G​o​o​g​l​e​ ​A​I​ ​S​t​u​d​i​o​ ​p​r​e​ ​r​o​z​p​o​z​n​á​v​a​n​i​e​ ​d​o​k​l​a​d​o​v​.
		 */
		geminiApiKeyHint: string
		/**
		 * P​r​i​e​č​i​n​o​k​ ​s​ ​d​o​k​l​a​d​m​i
		 */
		receiptsFolder: string
		/**
		 * V​y​b​e​r​t​e​ ​p​r​i​e​č​i​n​o​k
		 */
		receiptsFolderPlaceholder: string
		/**
		 * P​r​i​e​č​i​n​o​k​,​ ​k​d​e​ ​s​ú​ ​u​l​o​ž​e​n​é​ ​f​o​t​k​y​ ​d​o​k​l​a​d​o​v​.
		 */
		receiptsFolderHint: string
		/**
		 * V​y​b​r​a​ť
		 */
		browseFolder: string
		/**
		 * Z​o​b​r​a​z​i​ť
		 */
		showApiKey: string
		/**
		 * S​k​r​y​ť
		 */
		hideApiKey: string
		/**
		 * N​a​s​t​a​v​e​n​i​a​ ​d​o​k​l​a​d​o​v​ ​b​o​l​i​ ​u​l​o​ž​e​n​é
		 */
		receiptSettingsSaved: string
		/**
		 * U​m​i​e​s​t​n​e​n​i​e​ ​d​a​t​a​b​á​z​y
		 */
		dbLocationSection: string
		/**
		 * A​k​t​u​á​l​n​e​ ​u​m​i​e​s​t​n​e​n​i​e
		 */
		dbLocationCurrent: string
		/**
		 * V​l​a​s​t​n​á​ ​c​e​s​t​a
		 */
		dbLocationCustom: string
		/**
		 * P​r​e​d​v​o​l​e​n​á​ ​c​e​s​t​a
		 */
		dbLocationDefault: string
		/**
		 * Z​m​e​n​i​ť​ ​u​m​i​e​s​t​n​e​n​i​e​.​.​.
		 */
		dbLocationChange: string
		/**
		 * O​t​v​o​r​i​ť​ ​p​r​i​e​č​i​n​o​k
		 */
		dbLocationOpenFolder: string
		/**
		 * D​a​t​a​b​á​z​u​ ​m​ô​ž​e​t​e​ ​p​r​e​s​u​n​ú​ť​ ​n​a​ ​G​o​o​g​l​e​ ​D​r​i​v​e​,​ ​N​A​S​ ​a​l​e​b​o​ ​i​n​ý​ ​z​d​i​e​ľ​a​n​ý​ ​p​r​i​e​č​i​n​o​k​ ​p​r​e​ ​p​o​u​ž​i​t​i​e​ ​n​a​ ​v​i​a​c​e​r​ý​c​h​ ​P​C​.
		 */
		dbLocationHint: string
		/**
		 * P​r​e​s​ú​v​a​m​ ​d​a​t​a​b​á​z​u​.​.​.
		 */
		dbLocationMoving: string
		/**
		 * D​a​t​a​b​á​z​a​ ​b​o​l​a​ ​ú​s​p​e​š​n​e​ ​p​r​e​s​u​n​u​t​á
		 */
		dbLocationMoveSuccess: string
		/**
		 * N​e​p​o​d​a​r​i​l​o​ ​s​a​ ​p​r​e​s​u​n​ú​ť​ ​d​a​t​a​b​á​z​u​:​ ​{​e​r​r​o​r​}
		 * @param {string} error
		 */
		dbLocationMoveError: RequiredParams<'error'>
		/**
		 * C​i​e​ľ​o​v​ý​ ​p​r​i​e​č​i​n​o​k​ ​u​ž​ ​o​b​s​a​h​u​j​e​ ​d​a​t​a​b​á​z​u
		 */
		dbLocationTargetHasDb: string
		/**
		 * D​a​t​a​b​á​z​a​ ​b​o​l​a​ ​a​k​t​u​a​l​i​z​o​v​a​n​á​ ​n​o​v​š​o​u​ ​v​e​r​z​i​o​u​ ​a​p​l​i​k​á​c​i​e​.​ ​R​e​ž​i​m​ ​l​e​n​ ​n​a​ ​č​í​t​a​n​i​e​.
		 */
		readOnlyBanner: string
		/**
		 * S​k​o​n​t​r​o​l​o​v​a​ť​ ​a​k​t​u​a​l​i​z​á​c​i​e
		 */
		readOnlyCheckUpdates: string
	}
	backup: {
		/**
		 * P​o​t​v​r​d​i​ť​ ​o​b​n​o​v​e​n​i​e
		 */
		confirmRestoreTitle: string
		/**
		 * D​á​t​u​m​ ​z​á​l​o​h​y​:
		 */
		backupDate: string
		/**
		 * V​e​ľ​k​o​s​ť​:
		 */
		backupSize: string
		/**
		 * O​b​s​a​h​u​j​e​:
		 */
		backupContains: string
		/**
		 * {​v​e​h​i​c​l​e​s​}​ ​v​o​z​i​d​i​e​l​,​ ​{​t​r​i​p​s​}​ ​j​á​z​d
		 * @param {number} trips
		 * @param {number} vehicles
		 */
		vehiclesAndTrips: RequiredParams<'trips' | 'vehicles'>
		/**
		 * A​k​t​u​á​l​n​e​ ​d​á​t​a​ ​b​u​d​ú​ ​p​r​e​p​í​s​a​n​é​!​ ​A​k​ ​s​i​ ​c​h​c​e​t​e​ ​z​a​c​h​o​v​a​ť​ ​a​k​t​u​á​l​n​y​ ​s​t​a​v​,​ ​v​y​t​v​o​r​t​e​ ​s​i​ ​n​a​j​p​r​v​ ​z​á​l​o​h​u​ ​m​a​n​u​á​l​n​e​.
		 */
		restoreWarning: string
		/**
		 * O​b​n​o​v​i​ť​ ​z​á​l​o​h​u
		 */
		restoreBackup: string
		/**
		 * P​o​t​v​r​d​i​ť​ ​o​d​s​t​r​á​n​e​n​i​e
		 */
		confirmDeleteTitle: string
		/**
		 * T​á​t​o​ ​z​á​l​o​h​a​ ​b​u​d​e​ ​t​r​v​a​l​o​ ​o​d​s​t​r​á​n​e​n​á​!
		 */
		deleteWarning: string
	}
	confirm: {
		/**
		 * O​d​s​t​r​á​n​i​ť​ ​v​o​z​i​d​l​o
		 */
		deleteVehicleTitle: string
		/**
		 * N​a​o​z​a​j​ ​c​h​c​e​t​e​ ​o​d​s​t​r​á​n​i​ť​ ​v​o​z​i​d​l​o​ ​"​{​n​a​m​e​}​"​?
		 * @param {string} name
		 */
		deleteVehicleMessage: RequiredParams<'name'>
		/**
		 * O​d​s​t​r​á​n​i​ť​ ​z​á​z​n​a​m
		 */
		deleteRecordTitle: string
		/**
		 * N​a​o​z​a​j​ ​c​h​c​e​t​e​ ​o​d​s​t​r​á​n​i​ť​ ​t​e​n​t​o​ ​z​á​z​n​a​m​?
		 */
		deleteRecordMessage: string
		/**
		 * O​d​s​t​r​á​n​i​ť​ ​d​o​k​l​a​d
		 */
		deleteReceiptTitle: string
		/**
		 * N​a​o​z​a​j​ ​c​h​c​e​t​e​ ​o​d​s​t​r​á​n​i​ť​ ​d​o​k​l​a​d​ ​"​{​n​a​m​e​}​"​?
		 * @param {string} name
		 */
		deleteReceiptMessage: RequiredParams<'name'>
	}
	receipts: {
		/**
		 * D​o​k​l​a​d​y
		 */
		title: string
		/**
		 * S​k​e​n​o​v​a​ť​ ​p​r​i​e​č​i​n​o​k
		 */
		scanFolder: string
		/**
		 * S​k​e​n​u​j​e​m​.​.​.
		 */
		scanning: string
		/**
		 * R​o​z​p​o​z​n​a​ť​ ​d​á​t​a
		 */
		recognizeData: string
		/**
		 * R​o​z​p​o​z​n​á​v​a​m​ ​{​c​u​r​r​e​n​t​}​/​{​t​o​t​a​l​}​.​.​.
		 * @param {number} current
		 * @param {number} total
		 */
		recognizing: RequiredParams<'current' | 'total'>
		/**
		 * N​a​č​í​t​a​ť
		 */
		sync: string
		/**
		 * S​y​n​c​h​r​o​n​i​z​u​j​e​m​.​.​.
		 */
		syncing: string
		/**
		 * S​p​r​a​c​o​v​a​ť​ ​č​a​k​a​j​ú​c​e​ ​(​{​c​o​u​n​t​}​)
		 * @param {number} count
		 */
		processPending: RequiredParams<'count'>
		/**
		 * S​p​r​a​c​o​v​á​v​a​m​.​.​.
		 */
		processing: string
		/**
		 * S​p​r​a​c​o​v​á​v​a​m​ ​{​c​u​r​r​e​n​t​}​/​{​t​o​t​a​l​}​.​.​.
		 * @param {number} current
		 * @param {number} total
		 */
		processingProgress: RequiredParams<'current' | 'total'>
		/**
		 * F​u​n​k​c​i​a​ ​d​o​k​l​a​d​o​v​ ​n​i​e​ ​j​e​ ​n​a​k​o​n​f​i​g​u​r​o​v​a​n​á​.
		 */
		notConfigured: string
		/**
		 * V​y​t​v​o​r​t​e​ ​s​ú​b​o​r​ ​s​ ​n​á​z​v​o​m
		 */
		configurePrompt: string
		/**
		 * l​o​c​a​l​.​s​e​t​t​i​n​g​s​.​j​s​o​n
		 */
		configurePromptFile: string
		/**
		 * s​ ​n​a​s​l​e​d​u​j​ú​c​i​m​ ​o​b​s​a​h​o​m​:
		 */
		configurePromptSuffix: string
		/**
		 * P​o​z​n​á​m​k​a​:​ ​N​a​ ​W​i​n​d​o​w​s​ ​p​o​u​ž​í​v​a​j​t​e​ ​d​v​o​j​i​t​é​ ​s​p​ä​t​n​é​ ​l​o​m​k​y​ ​(​\​\​)​ ​v​ ​c​e​s​t​á​c​h​.
		 */
		configNote: string
		/**
		 * O​t​v​o​r​i​ť​ ​p​r​i​e​č​i​n​o​k
		 */
		openConfigFolder: string
		/**
		 * S​k​e​n​o​v​a​n​i​e​ ​d​o​k​l​a​d​o​v​ ​n​i​e​ ​j​e​ ​n​a​k​o​n​f​i​g​u​r​o​v​a​n​é
		 */
		notConfiguredTitle: string
		/**
		 * P​r​e​ ​p​o​u​ž​í​v​a​n​i​e​ ​t​e​j​t​o​ ​f​u​n​k​c​i​e​ ​p​o​t​r​e​b​u​j​e​t​e​:
		 */
		notConfiguredDescription: string
		/**
		 * N​a​s​t​a​v​i​ť​ ​G​e​m​i​n​i​ ​A​P​I​ ​k​ľ​ú​č​ ​(​z​ ​G​o​o​g​l​e​ ​A​I​ ​S​t​u​d​i​o​)
		 */
		notConfiguredApiKey: string
		/**
		 * V​y​b​r​a​ť​ ​p​r​i​e​č​i​n​o​k​ ​s​ ​d​o​k​l​a​d​m​i
		 */
		notConfiguredFolder: string
		/**
		 * P​r​e​j​s​ť​ ​d​o​ ​n​a​s​t​a​v​e​n​í
		 */
		goToSettings: string
		/**
		 * N​e​p​l​a​t​n​á​ ​š​t​r​u​k​t​ú​r​a​ ​p​r​i​e​č​i​n​k​a
		 */
		folderStructureWarning: string
		/**
		 * P​r​i​e​č​i​n​o​k​ ​m​u​s​í​ ​o​b​s​a​h​o​v​a​ť​ ​b​u​ď​ ​l​e​n​ ​s​ú​b​o​r​y​,​ ​a​l​e​b​o​ ​l​e​n​ ​p​r​i​e​č​i​n​k​y​ ​s​ ​n​á​z​v​a​m​i​ ​r​o​k​o​v​ ​(​2​0​2​4​,​ ​2​0​2​5​,​ ​.​.​.​)
		 */
		folderStructureHint: string
		/**
		 * D​á​t​u​m​ ​d​o​k​l​a​d​u​ ​(​{​r​e​c​e​i​p​t​Y​e​a​r​}​)​ ​n​e​z​o​d​p​o​v​e​d​á​ ​p​r​i​e​č​i​n​k​u​ ​(​{​f​o​l​d​e​r​Y​e​a​r​}​)
		 * @param {number} folderYear
		 * @param {number} receiptYear
		 */
		dateMismatch: RequiredParams<'folderYear' | 'receiptYear'>
		/**
		 * V​š​e​t​k​y
		 */
		filterAll: string
		/**
		 * N​e​o​v​e​r​e​n​é
		 */
		filterUnassigned: string
		/**
		 * N​a​ ​k​o​n​t​r​o​l​u
		 */
		filterNeedsReview: string
		/**
		 * T​a​n​k​o​v​a​n​i​e
		 */
		filterFuel: string
		/**
		 * I​n​é​ ​n​á​k​l​a​d​y
		 */
		filterOther: string
		/**
		 * {​c​o​u​n​t​}​/​{​t​o​t​a​l​}​ ​d​o​k​l​a​d​o​v​ ​o​v​e​r​e​n​ý​c​h
		 * @param {number} count
		 * @param {number} total
		 */
		allVerified: RequiredParams<'count' | 'total'>
		/**
		 * {​c​o​u​n​t​}​/​{​t​o​t​a​l​}​ ​o​v​e​r​e​n​ý​c​h
		 * @param {number} count
		 * @param {number} total
		 */
		verified: RequiredParams<'count' | 'total'>
		/**
		 * {​c​o​u​n​t​}​ ​n​e​o​v​e​r​e​n​ý​c​h
		 * @param {number} count
		 */
		unverified: RequiredParams<'count'>
		/**
		 * D​á​t​u​m​:
		 */
		date: string
		/**
		 * L​i​t​r​e​:
		 */
		liters: string
		/**
		 * C​e​n​a​:
		 */
		price: string
		/**
		 * S​t​a​n​i​c​a​:
		 */
		station: string
		/**
		 * J​a​z​d​a​:
		 */
		trip: string
		/**
		 * V​y​s​o​k​á​ ​i​s​t​o​t​a
		 */
		confidenceHigh: string
		/**
		 * S​t​r​e​d​n​á​ ​i​s​t​o​t​a
		 */
		confidenceMedium: string
		/**
		 * N​í​z​k​a​ ​i​s​t​o​t​a
		 */
		confidenceLow: string
		/**
		 * N​e​z​n​á​m​a​ ​i​s​t​o​t​a
		 */
		confidenceUnknown: string
		/**
		 * O​v​e​r​e​n​ý
		 */
		statusVerified: string
		/**
		 * N​a​ ​k​o​n​t​r​o​l​u
		 */
		statusNeedsReview: string
		/**
		 * N​e​o​v​e​r​e​n​ý
		 */
		statusUnverified: string
		/**
		 * O​t​v​o​r​i​ť
		 */
		open: string
		/**
		 * Z​n​o​v​u​ ​s​p​r​a​c​o​v​a​ť
		 */
		reprocess: string
		/**
		 * S​p​r​a​c​o​v​á​v​a​m​.​.​.
		 */
		reprocessing: string
		/**
		 * P​r​i​d​e​l​i​ť​ ​k​ ​j​a​z​d​e
		 */
		assignToTrip: string
		/**
		 * I​n​é​ ​n​á​k​l​a​d​y
		 */
		otherCost: string
		/**
		 * P​r​e​d​a​j​c​a​:
		 */
		vendor: string
		/**
		 * P​o​p​i​s​:
		 */
		description: string
		/**
		 * J​a​z​d​a​ ​u​ž​ ​m​á​ ​i​n​é​ ​n​á​k​l​a​d​y
		 */
		assignmentBlocked: string
		/**
		 * Ž​i​a​d​n​e​ ​d​o​k​l​a​d​y​.​ ​K​l​i​k​n​i​t​e​ ​n​a​ ​N​a​č​í​t​a​ť​ ​p​r​e​ ​n​a​č​í​t​a​n​i​e​ ​n​o​v​ý​c​h​.
		 */
		noReceipts: string
	}
	tripSelector: {
		/**
		 * P​r​i​d​e​l​i​ť​ ​d​o​k​l​a​d​ ​k​ ​j​a​z​d​e
		 */
		title: string
		/**
		 * N​i​e​ ​j​e​ ​v​y​b​r​a​t​é​ ​v​o​z​i​d​l​o
		 */
		noVehicleSelected: string
		/**
		 * N​a​č​í​t​a​v​a​m​ ​j​a​z​d​y​.​.​.
		 */
		loadingTrips: string
		/**
		 * N​e​p​o​d​a​r​i​l​o​ ​s​a​ ​n​a​č​í​t​a​ť​ ​j​a​z​d​y
		 */
		loadError: string
		/**
		 * Ž​i​a​d​n​e​ ​j​a​z​d​y​ ​n​a​ ​p​r​i​d​e​l​e​n​i​e​.
		 */
		noTrips: string
		/**
		 * u​ž​ ​m​á​:
		 */
		alreadyHas: string
	}
	toast: {
		/**
		 * V​o​z​i​d​l​o​ ​b​o​l​o​ ​ú​s​p​e​š​n​e​ ​u​l​o​ž​e​n​é
		 */
		vehicleSaved: string
		/**
		 * V​o​z​i​d​l​o​ ​b​o​l​o​ ​o​d​s​t​r​á​n​e​n​é
		 */
		vehicleDeleted: string
		/**
		 * N​a​s​t​a​v​e​n​i​a​ ​b​o​l​i​ ​ú​s​p​e​š​n​e​ ​u​l​o​ž​e​n​é
		 */
		settingsSaved: string
		/**
		 * Z​á​l​o​h​a​ ​b​o​l​a​ ​ú​s​p​e​š​n​e​ ​v​y​t​v​o​r​e​n​á
		 */
		backupCreated: string
		/**
		 * Z​á​l​o​h​a​ ​b​o​l​a​ ​ú​s​p​e​š​n​e​ ​o​b​n​o​v​e​n​á​.​ ​A​p​l​i​k​á​c​i​a​ ​s​a​ ​r​e​š​t​a​r​t​u​j​e​.
		 */
		backupRestored: string
		/**
		 * Z​á​l​o​h​a​ ​b​o​l​a​ ​o​d​s​t​r​á​n​e​n​á
		 */
		backupDeleted: string
		/**
		 * D​o​k​l​a​d​ ​b​o​l​ ​o​d​s​t​r​á​n​e​n​ý
		 */
		receiptDeleted: string
		/**
		 * D​o​k​l​a​d​ ​"​{​n​a​m​e​}​"​ ​b​o​l​ ​z​n​o​v​u​ ​s​p​r​a​c​o​v​a​n​ý
		 * @param {string} name
		 */
		receiptReprocessed: RequiredParams<'name'>
		/**
		 * D​o​k​l​a​d​ ​b​o​l​ ​p​r​i​d​e​l​e​n​ý​ ​k​ ​j​a​z​d​e
		 */
		receiptAssigned: string
		/**
		 * N​a​č​í​t​a​n​ý​c​h​ ​{​c​o​u​n​t​}​ ​n​o​v​ý​c​h​ ​d​o​k​l​a​d​o​v
		 * @param {number} count
		 */
		receiptsLoaded: RequiredParams<'count'>
		/**
		 * N​a​č​í​t​a​n​ý​c​h​ ​{​c​o​u​n​t​}​ ​d​o​k​l​a​d​o​v​ ​(​{​e​r​r​o​r​s​}​ ​c​h​ý​b​)
		 * @param {number} count
		 * @param {number} errors
		 */
		receiptsLoadedWithErrors: RequiredParams<'count' | 'errors'>
		/**
		 * S​p​r​a​c​o​v​a​n​ý​c​h​ ​{​c​o​u​n​t​}​ ​d​o​k​l​a​d​o​v
		 * @param {number} count
		 */
		receiptsProcessed: RequiredParams<'count'>
		/**
		 * S​p​r​a​c​o​v​a​n​ý​c​h​ ​{​c​o​u​n​t​}​ ​d​o​k​l​a​d​o​v​ ​(​{​e​r​r​o​r​s​}​ ​c​h​ý​b​)
		 * @param {number} count
		 * @param {number} errors
		 */
		receiptsProcessedWithErrors: RequiredParams<'count' | 'errors'>
		/**
		 * N​á​j​d​e​n​ý​c​h​ ​{​c​o​u​n​t​}​ ​n​o​v​ý​c​h​ ​s​ú​b​o​r​o​v
		 * @param {number} count
		 */
		foundNewReceipts: RequiredParams<'count'>
		/**
		 * Ž​i​a​d​n​e​ ​n​o​v​é​ ​s​ú​b​o​r​y
		 */
		noNewReceipts: string
		/**
		 * Ž​i​a​d​n​e​ ​č​a​k​a​j​ú​c​e​ ​d​o​k​l​a​d​y
		 */
		noPendingReceipts: string
		/**
		 * N​e​p​o​d​a​r​i​l​o​ ​s​a​ ​u​l​o​ž​i​ť​ ​v​o​z​i​d​l​o​:​ ​{​e​r​r​o​r​}
		 * @param {string} error
		 */
		errorSaveVehicle: RequiredParams<'error'>
		/**
		 * N​e​p​o​d​a​r​i​l​o​ ​s​a​ ​o​d​s​t​r​á​n​i​ť​ ​v​o​z​i​d​l​o​:​ ​{​e​r​r​o​r​}
		 * @param {string} error
		 */
		errorDeleteVehicle: RequiredParams<'error'>
		/**
		 * N​e​p​o​d​a​r​i​l​o​ ​s​a​ ​n​a​s​t​a​v​i​ť​ ​a​k​t​í​v​n​e​ ​v​o​z​i​d​l​o​:​ ​{​e​r​r​o​r​}
		 * @param {string} error
		 */
		errorSetActiveVehicle: RequiredParams<'error'>
		/**
		 * N​e​p​o​d​a​r​i​l​o​ ​s​a​ ​u​l​o​ž​i​ť​ ​n​a​s​t​a​v​e​n​i​a​:​ ​{​e​r​r​o​r​}
		 * @param {string} error
		 */
		errorSaveSettings: RequiredParams<'error'>
		/**
		 * N​e​p​o​d​a​r​i​l​o​ ​s​a​ ​v​y​t​v​o​r​i​ť​ ​z​á​l​o​h​u​:​ ​{​e​r​r​o​r​}
		 * @param {string} error
		 */
		errorCreateBackup: RequiredParams<'error'>
		/**
		 * N​e​p​o​d​a​r​i​l​o​ ​s​a​ ​n​a​č​í​t​a​ť​ ​i​n​f​o​r​m​á​c​i​e​ ​o​ ​z​á​l​o​h​e​:​ ​{​e​r​r​o​r​}
		 * @param {string} error
		 */
		errorGetBackupInfo: RequiredParams<'error'>
		/**
		 * N​e​p​o​d​a​r​i​l​o​ ​s​a​ ​o​b​n​o​v​i​ť​ ​z​á​l​o​h​u​:​ ​{​e​r​r​o​r​}
		 * @param {string} error
		 */
		errorRestoreBackup: RequiredParams<'error'>
		/**
		 * N​e​p​o​d​a​r​i​l​o​ ​s​a​ ​o​d​s​t​r​á​n​i​ť​ ​z​á​l​o​h​u​:​ ​{​e​r​r​o​r​}
		 * @param {string} error
		 */
		errorDeleteBackup: RequiredParams<'error'>
		/**
		 * N​e​p​o​d​a​r​i​l​o​ ​s​a​ ​n​a​č​í​t​a​ť​ ​d​o​k​l​a​d​y
		 */
		errorLoadReceipts: string
		/**
		 * N​e​p​o​d​a​r​i​l​o​ ​s​a​ ​s​y​n​c​h​r​o​n​i​z​o​v​a​ť​:​ ​{​e​r​r​o​r​}
		 * @param {string} error
		 */
		errorSyncReceipts: RequiredParams<'error'>
		/**
		 * N​e​p​o​d​a​r​i​l​o​ ​s​a​ ​s​p​r​a​c​o​v​a​ť​:​ ​{​e​r​r​o​r​}
		 * @param {string} error
		 */
		errorProcessReceipts: RequiredParams<'error'>
		/**
		 * N​e​p​o​d​a​r​i​l​o​ ​s​a​ ​o​d​s​t​r​á​n​i​ť​ ​d​o​k​l​a​d
		 */
		errorDeleteReceipt: string
		/**
		 * N​e​p​o​d​a​r​i​l​o​ ​s​a​ ​s​p​r​a​c​o​v​a​ť​ ​"​{​n​a​m​e​}​"​:​ ​{​e​r​r​o​r​}
		 * @param {string} error
		 * @param {string} name
		 */
		errorReprocessReceipt: RequiredParams<'error' | 'name'>
		/**
		 * N​e​p​o​d​a​r​i​l​o​ ​s​a​ ​p​r​i​d​e​l​i​ť​ ​d​o​k​l​a​d​:​ ​{​e​r​r​o​r​}
		 * @param {string} error
		 */
		errorAssignReceipt: RequiredParams<'error'>
		/**
		 * N​e​p​o​d​a​r​i​l​o​ ​s​a​ ​o​t​v​o​r​i​ť​ ​s​ú​b​o​r
		 */
		errorOpenFile: string
		/**
		 * N​e​p​o​d​a​r​i​l​o​ ​s​a​ ​v​y​t​v​o​r​i​ť​ ​z​á​z​n​a​m
		 */
		errorCreateTrip: string
		/**
		 * N​e​p​o​d​a​r​i​l​o​ ​s​a​ ​a​k​t​u​a​l​i​z​o​v​a​ť​ ​z​á​z​n​a​m
		 */
		errorUpdateTrip: string
		/**
		 * N​e​p​o​d​a​r​i​l​o​ ​s​a​ ​o​d​s​t​r​á​n​i​ť​ ​z​á​z​n​a​m
		 */
		errorDeleteTrip: string
		/**
		 * N​e​p​o​d​a​r​i​l​o​ ​s​a​ ​p​r​e​s​u​n​ú​ť​ ​z​á​z​n​a​m
		 */
		errorMoveTrip: string
		/**
		 * N​e​p​o​d​a​r​i​l​o​ ​s​a​ ​p​r​i​d​a​ť​ ​j​a​z​d​u​.​ ​S​k​ú​s​t​e​ ​t​o​ ​z​n​o​v​a​.
		 */
		errorAddCompensationTrip: string
		/**
		 * E​x​p​o​r​t​ ​z​l​y​h​a​l​:​ ​{​e​r​r​o​r​}
		 * @param {string} error
		 */
		errorExport: RequiredParams<'error'>
		/**
		 * N​a​j​p​r​v​ ​v​y​b​e​r​t​e​ ​v​o​z​i​d​l​o
		 */
		errorSelectVehicleFirst: string
		/**
		 * N​a​j​p​r​v​ ​n​a​s​t​a​v​t​e​ ​p​r​i​e​č​i​n​o​k​ ​a​ ​A​P​I​ ​k​ľ​ú​č​ ​v​ ​N​a​s​t​a​v​e​n​i​a​c​h
		 */
		errorSetApiKeyFirst: string
		/**
		 * N​a​j​p​r​v​ ​n​a​s​t​a​v​t​e​ ​A​P​I​ ​k​ľ​ú​č​ ​v​ ​N​a​s​t​a​v​e​n​i​a​c​h
		 */
		errorSetApiKeyOnlyFirst: string
	}
	'export': {
		/**
		 * K​N​I​H​A​ ​J​Á​Z​D
		 */
		pageTitle: string
		/**
		 * F​i​r​m​a​:
		 */
		headerCompany: string
		/**
		 * I​Č​O​:
		 */
		headerIco: string
		/**
		 * V​o​z​i​d​l​o​:
		 */
		headerVehicle: string
		/**
		 * Š​P​Z​:
		 */
		headerLicensePlate: string
		/**
		 * N​á​d​r​ž​:
		 */
		headerTankSize: string
		/**
		 * T​P​ ​s​p​o​t​r​e​b​a​:
		 */
		headerTpConsumption: string
		/**
		 * R​o​k​:
		 */
		headerYear: string
		/**
		 * B​a​t​é​r​i​a​:
		 */
		headerBatteryCapacity: string
		/**
		 * Z​á​k​l​a​d​.​ ​s​p​o​t​r​e​b​a​:
		 */
		headerBaselineConsumption: string
		/**
		 * V​I​N​:
		 */
		headerVin: string
		/**
		 * V​o​d​i​č​:
		 */
		headerDriver: string
		/**
		 * D​á​t​u​m
		 */
		colDate: string
		/**
		 * O​d​k​i​a​ľ
		 */
		colOrigin: string
		/**
		 * K​a​m
		 */
		colDestination: string
		/**
		 * Ú​č​e​l
		 */
		colPurpose: string
		/**
		 * K​m
		 */
		colKm: string
		/**
		 * O​D​O
		 */
		colOdo: string
		/**
		 * P​H​M​ ​L
		 */
		colFuelLiters: string
		/**
		 * €​ ​P​H​M
		 */
		colFuelCost: string
		/**
		 * €​ ​I​n​é
		 */
		colOtherCosts: string
		/**
		 * P​o​z​n​á​m​k​a
		 */
		colNote: string
		/**
		 * Z​o​s​t​.
		 */
		colRemaining: string
		/**
		 * S​p​o​t​r​.
		 */
		colConsumption: string
		/**
		 * k​W​h
		 */
		colEnergyKwh: string
		/**
		 * €​ ​E​n​e​r​g​.
		 */
		colEnergyCost: string
		/**
		 * B​a​t​é​r​i​a
		 */
		colBatteryRemaining: string
		/**
		 * k​W​h​/​1​0​0
		 */
		colEnergyRate: string
		/**
		 * C​e​l​k​o​m​ ​k​m
		 */
		footerTotalKm: string
		/**
		 * C​e​l​k​o​m​ ​P​H​M
		 */
		footerTotalFuel: string
		/**
		 * I​n​é​ ​n​á​k​l​a​d​y
		 */
		footerOtherCosts: string
		/**
		 * P​r​i​e​m​e​r​n​á​ ​s​p​o​t​r​e​b​a
		 */
		footerAvgConsumption: string
		/**
		 * O​d​c​h​ý​l​k​a​ ​o​d​ ​T​P
		 */
		footerDeviation: string
		/**
		 * T​P​ ​n​o​r​m​a
		 */
		footerTpNorm: string
		/**
		 * C​e​l​k​o​m​ ​e​n​e​r​g​i​a
		 */
		footerTotalEnergy: string
		/**
		 * P​r​i​e​m​e​r​n​á​ ​s​p​o​t​r​e​b​a
		 */
		footerAvgEnergyRate: string
		/**
		 * Z​á​k​l​a​d​.​ ​n​o​r​m​a
		 */
		footerBaselineNorm: string
		/**
		 * P​r​e​ ​e​x​p​o​r​t​ ​d​o​ ​P​D​F​ ​p​o​u​ž​i​t​e​ ​C​t​r​l​+​P​ ​→​ ​U​l​o​ž​i​ť​ ​a​k​o​ ​P​D​F
		 */
		printHint: string
	}
	update: {
		/**
		 * A​k​t​u​a​l​i​z​á​c​i​e
		 */
		sectionTitle: string
		/**
		 * V​e​r​z​i​a
		 */
		currentVersion: string
		/**
		 * S​k​o​n​t​r​o​l​o​v​a​ť​ ​a​k​t​u​a​l​i​z​á​c​i​e
		 */
		checkForUpdates: string
		/**
		 * A​k​t​u​a​l​i​z​o​v​a​ť
		 */
		updateNow: string
		/**
		 * N​e​s​k​ô​r
		 */
		later: string
		/**
		 * K​o​n​t​r​o​l​u​j​e​m​.​.​.
		 */
		checking: string
		/**
		 * A​p​l​i​k​á​c​i​a​ ​j​e​ ​a​k​t​u​á​l​n​a
		 */
		upToDate: string
		/**
		 * D​o​s​t​u​p​n​á​ ​a​k​t​u​a​l​i​z​á​c​i​a
		 */
		available: string
		/**
		 * D​o​s​t​u​p​n​á​ ​v​e​r​z​i​a​ ​{​v​e​r​s​i​o​n​}
		 * @param {string} version
		 */
		availableVersion: RequiredParams<'version'>
		/**
		 * S​ť​a​h​u​j​e​m​.​.​.
		 */
		downloading: string
		/**
		 * S​ť​a​h​o​v​a​n​i​e​:​ ​{​p​e​r​c​e​n​t​}​%
		 * @param {string} percent
		 */
		downloadProgress: RequiredParams<'percent'>
		/**
		 * I​n​š​t​a​l​u​j​e​m​.​.​.
		 */
		installing: string
		/**
		 * D​o​s​t​u​p​n​á​ ​a​k​t​u​a​l​i​z​á​c​i​a
		 */
		modalTitle: string
		/**
		 * V​e​r​z​i​a​ ​{​v​e​r​s​i​o​n​}​ ​j​e​ ​p​r​i​p​r​a​v​e​n​á​ ​n​a​ ​i​n​š​t​a​l​á​c​i​u​.
		 * @param {string} version
		 */
		modalBody: RequiredParams<'version'>
		/**
		 * Č​o​ ​j​e​ ​n​o​v​é​:
		 */
		releaseNotes: string
		/**
		 * N​e​p​o​d​a​r​i​l​o​ ​s​a​ ​s​k​o​n​t​r​o​l​o​v​a​ť​ ​a​k​t​u​a​l​i​z​á​c​i​e
		 */
		errorChecking: string
		/**
		 * S​k​o​n​t​r​o​l​u​j​t​e​ ​p​r​i​p​o​j​e​n​i​e​ ​k​ ​i​n​t​e​r​n​e​t​u
		 */
		errorNetwork: string
		/**
		 * S​ť​a​h​o​v​a​n​i​e​ ​p​r​e​r​u​š​e​n​é​,​ ​s​k​ú​s​t​e​ ​z​n​o​v​a
		 */
		errorDownloadInterrupted: string
		/**
		 * N​e​p​l​a​t​n​á​ ​s​i​g​n​a​t​ú​r​a​ ​a​k​t​u​a​l​i​z​á​c​i​e
		 */
		errorSignature: string
		/**
		 * N​e​d​o​s​t​a​t​o​k​ ​m​i​e​s​t​a​ ​n​a​ ​d​i​s​k​u
		 */
		errorDiskSpace: string
		/**
		 * S​e​r​v​e​r​ ​a​k​t​u​a​l​i​z​á​c​i​í​ ​n​e​d​o​s​t​u​p​n​ý
		 */
		errorServerUnavailable: string
		/**
		 * S​k​ú​s​i​ť​ ​z​n​o​v​a
		 */
		retry: string
		/**
		 * A​k​t​u​a​l​i​z​o​v​a​ť
		 */
		buttonUpdate: string
		/**
		 * N​e​s​k​ô​r
		 */
		buttonLater: string
		/**
		 * A​u​t​o​m​a​t​i​c​k​y​ ​k​o​n​t​r​o​l​o​v​a​ť​ ​p​r​i​ ​š​t​a​r​t​e
		 */
		autoCheckOnStart: string
	}
}

export type TranslationFunctions = {
	common: {
		/**
		 * Uložiť
		 */
		save: () => LocalizedString
		/**
		 * Zrušiť
		 */
		cancel: () => LocalizedString
		/**
		 * Odstrániť
		 */
		'delete': () => LocalizedString
		/**
		 * Upraviť
		 */
		edit: () => LocalizedString
		/**
		 * Pridať
		 */
		add: () => LocalizedString
		/**
		 * Zavrieť
		 */
		close: () => LocalizedString
		/**
		 * Potvrdiť
		 */
		confirm: () => LocalizedString
		/**
		 * Načítavam...
		 */
		loading: () => LocalizedString
		/**
		 * Žiadne dáta
		 */
		noData: () => LocalizedString
		/**
		 * Áno
		 */
		yes: () => LocalizedString
		/**
		 * Nie
		 */
		no: () => LocalizedString
	}
	app: {
		/**
		 * Kniha Jázd
		 */
		title: () => LocalizedString
		nav: {
			/**
			 * Kniha jázd
			 */
			logbook: () => LocalizedString
			/**
			 * Doklady
			 */
			receipts: () => LocalizedString
			/**
			 * Nastavenia
			 */
			settings: () => LocalizedString
		}
		/**
		 * Vozidlo:
		 */
		vehicleLabel: () => LocalizedString
		/**
		 * -- Vyberte vozidlo --
		 */
		vehiclePlaceholder: () => LocalizedString
		/**
		 * -- Žiadne vozidlá --
		 */
		noVehicles: () => LocalizedString
		/**
		 * Rok:
		 */
		yearLabel: () => LocalizedString
		/**
		 * Optimálna veľkosť okna
		 */
		resetWindowSize: () => LocalizedString
	}
	home: {
		/**
		 * Aktívne vozidlo
		 */
		activeVehicle: () => LocalizedString
		/**
		 * Export pre tlač
		 */
		exportForPrint: () => LocalizedString
		/**
		 * Exportujem...
		 */
		exporting: () => LocalizedString
		/**
		 * Žiadne vozidlo
		 */
		noVehicle: () => LocalizedString
		/**
		 * Prosím, vyberte vozidlo z hlavného menu alebo ho vytvorte v nastaveniach.
		 */
		noVehicleDescription: () => LocalizedString
		/**
		 * Prejsť do nastavení
		 */
		goToSettings: () => LocalizedString
	}
	stats: {
		/**
		 * Celkovo najazdené
		 */
		totalDriven: () => LocalizedString
		/**
		 * PHM
		 */
		fuel: () => LocalizedString
		/**
		 * Spotreba
		 */
		consumption: () => LocalizedString
		/**
		 * Odchýlka
		 */
		deviation: () => LocalizedString
		/**
		 * Zostatok
		 */
		remaining: () => LocalizedString
	}
	vehicle: {
		/**
		 * Názov
		 */
		name: () => LocalizedString
		/**
		 * ŠPZ
		 */
		licensePlate: () => LocalizedString
		/**
		 * Objem nádrže
		 */
		tankSize: () => LocalizedString
		/**
		 * Spotreba (TP)
		 */
		tpConsumption: () => LocalizedString
		/**
		 * Počiatočný stav ODO
		 */
		initialOdometer: () => LocalizedString
		/**
		 * Aktívne
		 */
		active: () => LocalizedString
		/**
		 * Nastaviť ako aktívne
		 */
		setAsActive: () => LocalizedString
		/**
		 * Typ vozidla
		 */
		vehicleType: () => LocalizedString
		/**
		 * Spaľovacie (ICE)
		 */
		vehicleTypeIce: () => LocalizedString
		/**
		 * Elektrické (BEV)
		 */
		vehicleTypeBev: () => LocalizedString
		/**
		 * Plug-in hybrid (PHEV)
		 */
		vehicleTypePhev: () => LocalizedString
		/**
		 * Kapacita batérie (kWh)
		 */
		batteryCapacity: () => LocalizedString
		/**
		 * Základná spotreba (kWh/100km)
		 */
		baselineConsumption: () => LocalizedString
		/**
		 * Počiatočný stav batérie (%)
		 */
		initialBatteryPercent: () => LocalizedString
		/**
		 * Typ vozidla nie je možné zmeniť po vytvorení záznamov
		 */
		typeChangeBlocked: () => LocalizedString
	}
	vehicleModal: {
		/**
		 * Pridať vozidlo
		 */
		addTitle: () => LocalizedString
		/**
		 * Upraviť vozidlo
		 */
		editTitle: () => LocalizedString
		/**
		 * napr. Škoda Octavia
		 */
		namePlaceholder: () => LocalizedString
		/**
		 * napr. BA123XY
		 */
		licensePlatePlaceholder: () => LocalizedString
		/**
		 * napr. 66
		 */
		tankSizePlaceholder: () => LocalizedString
		/**
		 * napr. 5.1
		 */
		tpConsumptionPlaceholder: () => LocalizedString
		/**
		 * napr. 50000
		 */
		initialOdometerPlaceholder: () => LocalizedString
		/**
		 * napr. 75
		 */
		batteryCapacityPlaceholder: () => LocalizedString
		/**
		 * napr. 18
		 */
		baselineConsumptionPlaceholder: () => LocalizedString
		/**
		 * napr. 100
		 */
		initialBatteryPlaceholder: () => LocalizedString
		/**
		 * Názov vozidla
		 */
		nameLabel: () => LocalizedString
		/**
		 * Evidenčné číslo (EČV)
		 */
		licensePlateLabel: () => LocalizedString
		/**
		 * Objem nádrže (litre)
		 */
		tankSizeLabel: () => LocalizedString
		/**
		 * Spotreba z TP (l/100km)
		 */
		tpConsumptionLabel: () => LocalizedString
		/**
		 * Počiatočný stav ODO (km)
		 */
		initialOdometerLabel: () => LocalizedString
		/**
		 * VIN
		 */
		vinLabel: () => LocalizedString
		/**
		 * napr. ABC123456789
		 */
		vinPlaceholder: () => LocalizedString
		/**
		 * Vodič
		 */
		driverLabel: () => LocalizedString
		/**
		 * napr. Janko Hraško
		 */
		driverPlaceholder: () => LocalizedString
		/**
		 * Typ vozidla
		 */
		vehicleTypeLabel: () => LocalizedString
		/**
		 * Kapacita batérie (kWh)
		 */
		batteryCapacityLabel: () => LocalizedString
		/**
		 * Základná spotreba (kWh/100km)
		 */
		baselineConsumptionLabel: () => LocalizedString
		/**
		 * Počiatočný stav batérie (%)
		 */
		initialBatteryLabel: () => LocalizedString
		/**
		 * Palivo
		 */
		fuelSection: () => LocalizedString
		/**
		 * Batéria
		 */
		batterySection: () => LocalizedString
	}
	trips: {
		/**
		 * Jazdy
		 */
		title: () => LocalizedString
		/**
		 * ({count})
		 */
		count: (arg: { count: number }) => LocalizedString
		/**
		 * Nový záznam
		 */
		newRecord: () => LocalizedString
		/**
		 * Prvý záznam
		 */
		firstRecord: () => LocalizedString
		/**
		 * Žiadne záznamy. Kliknite na "Nový záznam" pre pridanie jazdy.
		 */
		emptyState: () => LocalizedString
		columns: {
			/**
			 * Dátum
			 */
			date: () => LocalizedString
			/**
			 * Odkiaľ
			 */
			origin: () => LocalizedString
			/**
			 * Kam
			 */
			destination: () => LocalizedString
			/**
			 * Km
			 */
			km: () => LocalizedString
			/**
			 * ODO
			 */
			odo: () => LocalizedString
			/**
			 * Účel
			 */
			purpose: () => LocalizedString
			/**
			 * PHM (L)
			 */
			fuelLiters: () => LocalizedString
			/**
			 * Cena €
			 */
			fuelCost: () => LocalizedString
			/**
			 * l/100km
			 */
			consumptionRate: () => LocalizedString
			/**
			 * Zostatok
			 */
			remaining: () => LocalizedString
			/**
			 * Iné €
			 */
			otherCosts: () => LocalizedString
			/**
			 * Iné pozn.
			 */
			otherCostsNote: () => LocalizedString
			/**
			 * Akcie
			 */
			actions: () => LocalizedString
			/**
			 * Energia (kWh)
			 */
			energyKwh: () => LocalizedString
			/**
			 * Cena nab. €
			 */
			energyCost: () => LocalizedString
			/**
			 * kWh/100km
			 */
			energyRate: () => LocalizedString
			/**
			 * Batéria
			 */
			batteryRemaining: () => LocalizedString
			/**
			 * Batéria %
			 */
			batteryPercent: () => LocalizedString
		}
		/**
		 * Odkiaľ
		 */
		originPlaceholder: () => LocalizedString
		/**
		 * Kam
		 */
		destinationPlaceholder: () => LocalizedString
		/**
		 * Účel
		 */
		purposePlaceholder: () => LocalizedString
		/**
		 * Presunúť hore
		 */
		moveUp: () => LocalizedString
		/**
		 * Presunúť dole
		 */
		moveDown: () => LocalizedString
		/**
		 * Vložiť záznam nad
		 */
		insertAbove: () => LocalizedString
		/**
		 * Odstrániť záznam
		 */
		deleteRecord: () => LocalizedString
		/**
		 * Plná
		 */
		fullTank: () => LocalizedString
		/**
		 * Plné nabitie
		 */
		fullCharge: () => LocalizedString
		/**
		 * Korekcia stavu batérie (%)
		 */
		socOverride: () => LocalizedString
		/**
		 * Manuálne nastavenie stavu batérie pre korekciu odchýlok
		 */
		socOverrideHint: () => LocalizedString
		/**
		 * Manuálna korekcia SoC
		 */
		socOverrideIndicator: () => LocalizedString
		/**
		 * Čiastočné tankovanie
		 */
		partialFillup: () => LocalizedString
		/**
		 * Čiastočné nabitie
		 */
		partialCharge: () => LocalizedString
		/**
		 * Bez dokladu
		 */
		noReceipt: () => LocalizedString
		/**
		 * Odhad podľa TP
		 */
		estimatedRate: () => LocalizedString
		/**
		 * Odhad podľa základnej spotreby
		 */
		estimatedEnergyRate: () => LocalizedString
		legend: {
			/**
			 * čiastočné tankovanie
			 */
			partialFillup: () => LocalizedString
			/**
			 * bez dokladu
			 */
			noReceipt: () => LocalizedString
			/**
			 * vysoká spotreba
			 */
			highConsumption: () => LocalizedString
		}
	}
	compensation: {
		/**
		 * Prekročený zákonný limit spotreby
		 */
		title: () => LocalizedString
		/**
		 * Aktuálna odchýlka: {percent}% (limit: 20%)
		 */
		currentDeviation: (arg: { percent: string }) => LocalizedString
		/**
		 * Potrebných dodatočných km: {km} km
		 */
		additionalKmNeeded: (arg: { km: string }) => LocalizedString
		/**
		 * Hľadám vhodný návrh jazdy...
		 */
		searchingSuggestion: () => LocalizedString
		/**
		 * Návrh kompenzačnej jazdy:
		 */
		suggestionTitle: () => LocalizedString
		/**
		 * Začiatok:
		 */
		origin: () => LocalizedString
		/**
		 * Cieľ:
		 */
		destination: () => LocalizedString
		/**
		 * Vzdialenosť:
		 */
		distance: () => LocalizedString
		/**
		 * Účel:
		 */
		purpose: () => LocalizedString
		/**
		 * Poznámka: Toto je kompenzačná jazda (rovnaká poloha začiatku a cieľa)
		 */
		bufferNote: () => LocalizedString
		/**
		 * Pridať jazdu
		 */
		addTrip: () => LocalizedString
		/**
		 * Pridávam...
		 */
		adding: () => LocalizedString
	}
	settings: {
		/**
		 * Nastavenia
		 */
		title: () => LocalizedString
		/**
		 * Vozidlá
		 */
		vehiclesSection: () => LocalizedString
		/**
		 * Žiadne vozidlá. Vytvorte prvé vozidlo.
		 */
		noVehicles: () => LocalizedString
		/**
		 * + Pridať vozidlo
		 */
		addVehicle: () => LocalizedString
		/**
		 * Nastavenia spoločnosti
		 */
		companySection: () => LocalizedString
		/**
		 * Názov spoločnosti
		 */
		companyName: () => LocalizedString
		/**
		 * napr. Moja firma s.r.o.
		 */
		companyNamePlaceholder: () => LocalizedString
		/**
		 * IČO
		 */
		companyIco: () => LocalizedString
		/**
		 * napr. 12345678
		 */
		companyIcoPlaceholder: () => LocalizedString
		/**
		 * Účel kompenzačnej jazdy
		 */
		bufferTripPurpose: () => LocalizedString
		/**
		 * napr. služobná cesta
		 */
		bufferTripPurposePlaceholder: () => LocalizedString
		/**
		 * Tento účel sa použije pri plánovaní jázd na dodržanie 20% limitu spotreby.
		 */
		bufferTripPurposeHint: () => LocalizedString
		/**
		 * Uložiť nastavenia
		 */
		saveSettings: () => LocalizedString
		/**
		 * Záloha databázy
		 */
		backupSection: () => LocalizedString
		/**
		 * Zálohovať
		 */
		createBackup: () => LocalizedString
		/**
		 * Vytváram zálohu...
		 */
		creatingBackup: () => LocalizedString
		/**
		 * Dostupné zálohy
		 */
		availableBackups: () => LocalizedString
		/**
		 * Žiadne zálohy. Vytvorte prvú zálohu.
		 */
		noBackups: () => LocalizedString
		/**
		 * Obnoviť
		 */
		restore: () => LocalizedString
		/**
		 * Zobraziť v Prieskumníkovi
		 */
		revealWindows: () => LocalizedString
		/**
		 * Zobraziť vo Finderi
		 */
		revealMac: () => LocalizedString
		/**
		 * Zobraziť v Súboroch
		 */
		revealLinux: () => LocalizedString
		/**
		 * Jazyk
		 */
		languageSection: () => LocalizedString
		/**
		 * Jazyk aplikácie
		 */
		language: () => LocalizedString
		/**
		 * Vzhľad
		 */
		appearanceSection: () => LocalizedString
		/**
		 * Téma
		 */
		themeLabel: () => LocalizedString
		/**
		 * Podľa systému
		 */
		themeSystem: () => LocalizedString
		/**
		 * Svetlá
		 */
		themeLight: () => LocalizedString
		/**
		 * Tmavá
		 */
		themeDark: () => LocalizedString
		/**
		 * Skenovanie dokladov
		 */
		receiptScanningSection: () => LocalizedString
		/**
		 * Gemini API kľúč
		 */
		geminiApiKey: () => LocalizedString
		/**
		 * Zadajte API kľúč
		 */
		geminiApiKeyPlaceholder: () => LocalizedString
		/**
		 * API kľúč z Google AI Studio pre rozpoznávanie dokladov.
		 */
		geminiApiKeyHint: () => LocalizedString
		/**
		 * Priečinok s dokladmi
		 */
		receiptsFolder: () => LocalizedString
		/**
		 * Vyberte priečinok
		 */
		receiptsFolderPlaceholder: () => LocalizedString
		/**
		 * Priečinok, kde sú uložené fotky dokladov.
		 */
		receiptsFolderHint: () => LocalizedString
		/**
		 * Vybrať
		 */
		browseFolder: () => LocalizedString
		/**
		 * Zobraziť
		 */
		showApiKey: () => LocalizedString
		/**
		 * Skryť
		 */
		hideApiKey: () => LocalizedString
		/**
		 * Nastavenia dokladov boli uložené
		 */
		receiptSettingsSaved: () => LocalizedString
		/**
		 * Umiestnenie databázy
		 */
		dbLocationSection: () => LocalizedString
		/**
		 * Aktuálne umiestnenie
		 */
		dbLocationCurrent: () => LocalizedString
		/**
		 * Vlastná cesta
		 */
		dbLocationCustom: () => LocalizedString
		/**
		 * Predvolená cesta
		 */
		dbLocationDefault: () => LocalizedString
		/**
		 * Zmeniť umiestnenie...
		 */
		dbLocationChange: () => LocalizedString
		/**
		 * Otvoriť priečinok
		 */
		dbLocationOpenFolder: () => LocalizedString
		/**
		 * Databázu môžete presunúť na Google Drive, NAS alebo iný zdieľaný priečinok pre použitie na viacerých PC.
		 */
		dbLocationHint: () => LocalizedString
		/**
		 * Presúvam databázu...
		 */
		dbLocationMoving: () => LocalizedString
		/**
		 * Databáza bola úspešne presunutá
		 */
		dbLocationMoveSuccess: () => LocalizedString
		/**
		 * Nepodarilo sa presunúť databázu: {error}
		 */
		dbLocationMoveError: (arg: { error: string }) => LocalizedString
		/**
		 * Cieľový priečinok už obsahuje databázu
		 */
		dbLocationTargetHasDb: () => LocalizedString
		/**
		 * Databáza bola aktualizovaná novšou verziou aplikácie. Režim len na čítanie.
		 */
		readOnlyBanner: () => LocalizedString
		/**
		 * Skontrolovať aktualizácie
		 */
		readOnlyCheckUpdates: () => LocalizedString
	}
	backup: {
		/**
		 * Potvrdiť obnovenie
		 */
		confirmRestoreTitle: () => LocalizedString
		/**
		 * Dátum zálohy:
		 */
		backupDate: () => LocalizedString
		/**
		 * Veľkosť:
		 */
		backupSize: () => LocalizedString
		/**
		 * Obsahuje:
		 */
		backupContains: () => LocalizedString
		/**
		 * {vehicles} vozidiel, {trips} jázd
		 */
		vehiclesAndTrips: (arg: { trips: number, vehicles: number }) => LocalizedString
		/**
		 * Aktuálne dáta budú prepísané! Ak si chcete zachovať aktuálny stav, vytvorte si najprv zálohu manuálne.
		 */
		restoreWarning: () => LocalizedString
		/**
		 * Obnoviť zálohu
		 */
		restoreBackup: () => LocalizedString
		/**
		 * Potvrdiť odstránenie
		 */
		confirmDeleteTitle: () => LocalizedString
		/**
		 * Táto záloha bude trvalo odstránená!
		 */
		deleteWarning: () => LocalizedString
	}
	confirm: {
		/**
		 * Odstrániť vozidlo
		 */
		deleteVehicleTitle: () => LocalizedString
		/**
		 * Naozaj chcete odstrániť vozidlo "{name}"?
		 */
		deleteVehicleMessage: (arg: { name: string }) => LocalizedString
		/**
		 * Odstrániť záznam
		 */
		deleteRecordTitle: () => LocalizedString
		/**
		 * Naozaj chcete odstrániť tento záznam?
		 */
		deleteRecordMessage: () => LocalizedString
		/**
		 * Odstrániť doklad
		 */
		deleteReceiptTitle: () => LocalizedString
		/**
		 * Naozaj chcete odstrániť doklad "{name}"?
		 */
		deleteReceiptMessage: (arg: { name: string }) => LocalizedString
	}
	receipts: {
		/**
		 * Doklady
		 */
		title: () => LocalizedString
		/**
		 * Skenovať priečinok
		 */
		scanFolder: () => LocalizedString
		/**
		 * Skenujem...
		 */
		scanning: () => LocalizedString
		/**
		 * Rozpoznať dáta
		 */
		recognizeData: () => LocalizedString
		/**
		 * Rozpoznávam {current}/{total}...
		 */
		recognizing: (arg: { current: number, total: number }) => LocalizedString
		/**
		 * Načítať
		 */
		sync: () => LocalizedString
		/**
		 * Synchronizujem...
		 */
		syncing: () => LocalizedString
		/**
		 * Spracovať čakajúce ({count})
		 */
		processPending: (arg: { count: number }) => LocalizedString
		/**
		 * Spracovávam...
		 */
		processing: () => LocalizedString
		/**
		 * Spracovávam {current}/{total}...
		 */
		processingProgress: (arg: { current: number, total: number }) => LocalizedString
		/**
		 * Funkcia dokladov nie je nakonfigurovaná.
		 */
		notConfigured: () => LocalizedString
		/**
		 * Vytvorte súbor s názvom
		 */
		configurePrompt: () => LocalizedString
		/**
		 * local.settings.json
		 */
		configurePromptFile: () => LocalizedString
		/**
		 * s nasledujúcim obsahom:
		 */
		configurePromptSuffix: () => LocalizedString
		/**
		 * Poznámka: Na Windows používajte dvojité spätné lomky (\\) v cestách.
		 */
		configNote: () => LocalizedString
		/**
		 * Otvoriť priečinok
		 */
		openConfigFolder: () => LocalizedString
		/**
		 * Skenovanie dokladov nie je nakonfigurované
		 */
		notConfiguredTitle: () => LocalizedString
		/**
		 * Pre používanie tejto funkcie potrebujete:
		 */
		notConfiguredDescription: () => LocalizedString
		/**
		 * Nastaviť Gemini API kľúč (z Google AI Studio)
		 */
		notConfiguredApiKey: () => LocalizedString
		/**
		 * Vybrať priečinok s dokladmi
		 */
		notConfiguredFolder: () => LocalizedString
		/**
		 * Prejsť do nastavení
		 */
		goToSettings: () => LocalizedString
		/**
		 * Neplatná štruktúra priečinka
		 */
		folderStructureWarning: () => LocalizedString
		/**
		 * Priečinok musí obsahovať buď len súbory, alebo len priečinky s názvami rokov (2024, 2025, ...)
		 */
		folderStructureHint: () => LocalizedString
		/**
		 * Dátum dokladu ({receiptYear}) nezodpovedá priečinku ({folderYear})
		 */
		dateMismatch: (arg: { folderYear: number, receiptYear: number }) => LocalizedString
		/**
		 * Všetky
		 */
		filterAll: () => LocalizedString
		/**
		 * Neoverené
		 */
		filterUnassigned: () => LocalizedString
		/**
		 * Na kontrolu
		 */
		filterNeedsReview: () => LocalizedString
		/**
		 * Tankovanie
		 */
		filterFuel: () => LocalizedString
		/**
		 * Iné náklady
		 */
		filterOther: () => LocalizedString
		/**
		 * {count}/{total} dokladov overených
		 */
		allVerified: (arg: { count: number, total: number }) => LocalizedString
		/**
		 * {count}/{total} overených
		 */
		verified: (arg: { count: number, total: number }) => LocalizedString
		/**
		 * {count} neoverených
		 */
		unverified: (arg: { count: number }) => LocalizedString
		/**
		 * Dátum:
		 */
		date: () => LocalizedString
		/**
		 * Litre:
		 */
		liters: () => LocalizedString
		/**
		 * Cena:
		 */
		price: () => LocalizedString
		/**
		 * Stanica:
		 */
		station: () => LocalizedString
		/**
		 * Jazda:
		 */
		trip: () => LocalizedString
		/**
		 * Vysoká istota
		 */
		confidenceHigh: () => LocalizedString
		/**
		 * Stredná istota
		 */
		confidenceMedium: () => LocalizedString
		/**
		 * Nízka istota
		 */
		confidenceLow: () => LocalizedString
		/**
		 * Neznáma istota
		 */
		confidenceUnknown: () => LocalizedString
		/**
		 * Overený
		 */
		statusVerified: () => LocalizedString
		/**
		 * Na kontrolu
		 */
		statusNeedsReview: () => LocalizedString
		/**
		 * Neoverený
		 */
		statusUnverified: () => LocalizedString
		/**
		 * Otvoriť
		 */
		open: () => LocalizedString
		/**
		 * Znovu spracovať
		 */
		reprocess: () => LocalizedString
		/**
		 * Spracovávam...
		 */
		reprocessing: () => LocalizedString
		/**
		 * Prideliť k jazde
		 */
		assignToTrip: () => LocalizedString
		/**
		 * Iné náklady
		 */
		otherCost: () => LocalizedString
		/**
		 * Predajca:
		 */
		vendor: () => LocalizedString
		/**
		 * Popis:
		 */
		description: () => LocalizedString
		/**
		 * Jazda už má iné náklady
		 */
		assignmentBlocked: () => LocalizedString
		/**
		 * Žiadne doklady. Kliknite na Načítať pre načítanie nových.
		 */
		noReceipts: () => LocalizedString
	}
	tripSelector: {
		/**
		 * Prideliť doklad k jazde
		 */
		title: () => LocalizedString
		/**
		 * Nie je vybraté vozidlo
		 */
		noVehicleSelected: () => LocalizedString
		/**
		 * Načítavam jazdy...
		 */
		loadingTrips: () => LocalizedString
		/**
		 * Nepodarilo sa načítať jazdy
		 */
		loadError: () => LocalizedString
		/**
		 * Žiadne jazdy na pridelenie.
		 */
		noTrips: () => LocalizedString
		/**
		 * už má:
		 */
		alreadyHas: () => LocalizedString
	}
	toast: {
		/**
		 * Vozidlo bolo úspešne uložené
		 */
		vehicleSaved: () => LocalizedString
		/**
		 * Vozidlo bolo odstránené
		 */
		vehicleDeleted: () => LocalizedString
		/**
		 * Nastavenia boli úspešne uložené
		 */
		settingsSaved: () => LocalizedString
		/**
		 * Záloha bola úspešne vytvorená
		 */
		backupCreated: () => LocalizedString
		/**
		 * Záloha bola úspešne obnovená. Aplikácia sa reštartuje.
		 */
		backupRestored: () => LocalizedString
		/**
		 * Záloha bola odstránená
		 */
		backupDeleted: () => LocalizedString
		/**
		 * Doklad bol odstránený
		 */
		receiptDeleted: () => LocalizedString
		/**
		 * Doklad "{name}" bol znovu spracovaný
		 */
		receiptReprocessed: (arg: { name: string }) => LocalizedString
		/**
		 * Doklad bol pridelený k jazde
		 */
		receiptAssigned: () => LocalizedString
		/**
		 * Načítaných {count} nových dokladov
		 */
		receiptsLoaded: (arg: { count: number }) => LocalizedString
		/**
		 * Načítaných {count} dokladov ({errors} chýb)
		 */
		receiptsLoadedWithErrors: (arg: { count: number, errors: number }) => LocalizedString
		/**
		 * Spracovaných {count} dokladov
		 */
		receiptsProcessed: (arg: { count: number }) => LocalizedString
		/**
		 * Spracovaných {count} dokladov ({errors} chýb)
		 */
		receiptsProcessedWithErrors: (arg: { count: number, errors: number }) => LocalizedString
		/**
		 * Nájdených {count} nových súborov
		 */
		foundNewReceipts: (arg: { count: number }) => LocalizedString
		/**
		 * Žiadne nové súbory
		 */
		noNewReceipts: () => LocalizedString
		/**
		 * Žiadne čakajúce doklady
		 */
		noPendingReceipts: () => LocalizedString
		/**
		 * Nepodarilo sa uložiť vozidlo: {error}
		 */
		errorSaveVehicle: (arg: { error: string }) => LocalizedString
		/**
		 * Nepodarilo sa odstrániť vozidlo: {error}
		 */
		errorDeleteVehicle: (arg: { error: string }) => LocalizedString
		/**
		 * Nepodarilo sa nastaviť aktívne vozidlo: {error}
		 */
		errorSetActiveVehicle: (arg: { error: string }) => LocalizedString
		/**
		 * Nepodarilo sa uložiť nastavenia: {error}
		 */
		errorSaveSettings: (arg: { error: string }) => LocalizedString
		/**
		 * Nepodarilo sa vytvoriť zálohu: {error}
		 */
		errorCreateBackup: (arg: { error: string }) => LocalizedString
		/**
		 * Nepodarilo sa načítať informácie o zálohe: {error}
		 */
		errorGetBackupInfo: (arg: { error: string }) => LocalizedString
		/**
		 * Nepodarilo sa obnoviť zálohu: {error}
		 */
		errorRestoreBackup: (arg: { error: string }) => LocalizedString
		/**
		 * Nepodarilo sa odstrániť zálohu: {error}
		 */
		errorDeleteBackup: (arg: { error: string }) => LocalizedString
		/**
		 * Nepodarilo sa načítať doklady
		 */
		errorLoadReceipts: () => LocalizedString
		/**
		 * Nepodarilo sa synchronizovať: {error}
		 */
		errorSyncReceipts: (arg: { error: string }) => LocalizedString
		/**
		 * Nepodarilo sa spracovať: {error}
		 */
		errorProcessReceipts: (arg: { error: string }) => LocalizedString
		/**
		 * Nepodarilo sa odstrániť doklad
		 */
		errorDeleteReceipt: () => LocalizedString
		/**
		 * Nepodarilo sa spracovať "{name}": {error}
		 */
		errorReprocessReceipt: (arg: { error: string, name: string }) => LocalizedString
		/**
		 * Nepodarilo sa prideliť doklad: {error}
		 */
		errorAssignReceipt: (arg: { error: string }) => LocalizedString
		/**
		 * Nepodarilo sa otvoriť súbor
		 */
		errorOpenFile: () => LocalizedString
		/**
		 * Nepodarilo sa vytvoriť záznam
		 */
		errorCreateTrip: () => LocalizedString
		/**
		 * Nepodarilo sa aktualizovať záznam
		 */
		errorUpdateTrip: () => LocalizedString
		/**
		 * Nepodarilo sa odstrániť záznam
		 */
		errorDeleteTrip: () => LocalizedString
		/**
		 * Nepodarilo sa presunúť záznam
		 */
		errorMoveTrip: () => LocalizedString
		/**
		 * Nepodarilo sa pridať jazdu. Skúste to znova.
		 */
		errorAddCompensationTrip: () => LocalizedString
		/**
		 * Export zlyhal: {error}
		 */
		errorExport: (arg: { error: string }) => LocalizedString
		/**
		 * Najprv vyberte vozidlo
		 */
		errorSelectVehicleFirst: () => LocalizedString
		/**
		 * Najprv nastavte priečinok a API kľúč v Nastaveniach
		 */
		errorSetApiKeyFirst: () => LocalizedString
		/**
		 * Najprv nastavte API kľúč v Nastaveniach
		 */
		errorSetApiKeyOnlyFirst: () => LocalizedString
	}
	'export': {
		/**
		 * KNIHA JÁZD
		 */
		pageTitle: () => LocalizedString
		/**
		 * Firma:
		 */
		headerCompany: () => LocalizedString
		/**
		 * IČO:
		 */
		headerIco: () => LocalizedString
		/**
		 * Vozidlo:
		 */
		headerVehicle: () => LocalizedString
		/**
		 * ŠPZ:
		 */
		headerLicensePlate: () => LocalizedString
		/**
		 * Nádrž:
		 */
		headerTankSize: () => LocalizedString
		/**
		 * TP spotreba:
		 */
		headerTpConsumption: () => LocalizedString
		/**
		 * Rok:
		 */
		headerYear: () => LocalizedString
		/**
		 * Batéria:
		 */
		headerBatteryCapacity: () => LocalizedString
		/**
		 * Základ. spotreba:
		 */
		headerBaselineConsumption: () => LocalizedString
		/**
		 * VIN:
		 */
		headerVin: () => LocalizedString
		/**
		 * Vodič:
		 */
		headerDriver: () => LocalizedString
		/**
		 * Dátum
		 */
		colDate: () => LocalizedString
		/**
		 * Odkiaľ
		 */
		colOrigin: () => LocalizedString
		/**
		 * Kam
		 */
		colDestination: () => LocalizedString
		/**
		 * Účel
		 */
		colPurpose: () => LocalizedString
		/**
		 * Km
		 */
		colKm: () => LocalizedString
		/**
		 * ODO
		 */
		colOdo: () => LocalizedString
		/**
		 * PHM L
		 */
		colFuelLiters: () => LocalizedString
		/**
		 * € PHM
		 */
		colFuelCost: () => LocalizedString
		/**
		 * € Iné
		 */
		colOtherCosts: () => LocalizedString
		/**
		 * Poznámka
		 */
		colNote: () => LocalizedString
		/**
		 * Zost.
		 */
		colRemaining: () => LocalizedString
		/**
		 * Spotr.
		 */
		colConsumption: () => LocalizedString
		/**
		 * kWh
		 */
		colEnergyKwh: () => LocalizedString
		/**
		 * € Energ.
		 */
		colEnergyCost: () => LocalizedString
		/**
		 * Batéria
		 */
		colBatteryRemaining: () => LocalizedString
		/**
		 * kWh/100
		 */
		colEnergyRate: () => LocalizedString
		/**
		 * Celkom km
		 */
		footerTotalKm: () => LocalizedString
		/**
		 * Celkom PHM
		 */
		footerTotalFuel: () => LocalizedString
		/**
		 * Iné náklady
		 */
		footerOtherCosts: () => LocalizedString
		/**
		 * Priemerná spotreba
		 */
		footerAvgConsumption: () => LocalizedString
		/**
		 * Odchýlka od TP
		 */
		footerDeviation: () => LocalizedString
		/**
		 * TP norma
		 */
		footerTpNorm: () => LocalizedString
		/**
		 * Celkom energia
		 */
		footerTotalEnergy: () => LocalizedString
		/**
		 * Priemerná spotreba
		 */
		footerAvgEnergyRate: () => LocalizedString
		/**
		 * Základ. norma
		 */
		footerBaselineNorm: () => LocalizedString
		/**
		 * Pre export do PDF použite Ctrl+P → Uložiť ako PDF
		 */
		printHint: () => LocalizedString
	}
	update: {
		/**
		 * Aktualizácie
		 */
		sectionTitle: () => LocalizedString
		/**
		 * Verzia
		 */
		currentVersion: () => LocalizedString
		/**
		 * Skontrolovať aktualizácie
		 */
		checkForUpdates: () => LocalizedString
		/**
		 * Aktualizovať
		 */
		updateNow: () => LocalizedString
		/**
		 * Neskôr
		 */
		later: () => LocalizedString
		/**
		 * Kontrolujem...
		 */
		checking: () => LocalizedString
		/**
		 * Aplikácia je aktuálna
		 */
		upToDate: () => LocalizedString
		/**
		 * Dostupná aktualizácia
		 */
		available: () => LocalizedString
		/**
		 * Dostupná verzia {version}
		 */
		availableVersion: (arg: { version: string }) => LocalizedString
		/**
		 * Sťahujem...
		 */
		downloading: () => LocalizedString
		/**
		 * Sťahovanie: {percent}%
		 */
		downloadProgress: (arg: { percent: string }) => LocalizedString
		/**
		 * Inštalujem...
		 */
		installing: () => LocalizedString
		/**
		 * Dostupná aktualizácia
		 */
		modalTitle: () => LocalizedString
		/**
		 * Verzia {version} je pripravená na inštaláciu.
		 */
		modalBody: (arg: { version: string }) => LocalizedString
		/**
		 * Čo je nové:
		 */
		releaseNotes: () => LocalizedString
		/**
		 * Nepodarilo sa skontrolovať aktualizácie
		 */
		errorChecking: () => LocalizedString
		/**
		 * Skontrolujte pripojenie k internetu
		 */
		errorNetwork: () => LocalizedString
		/**
		 * Sťahovanie prerušené, skúste znova
		 */
		errorDownloadInterrupted: () => LocalizedString
		/**
		 * Neplatná signatúra aktualizácie
		 */
		errorSignature: () => LocalizedString
		/**
		 * Nedostatok miesta na disku
		 */
		errorDiskSpace: () => LocalizedString
		/**
		 * Server aktualizácií nedostupný
		 */
		errorServerUnavailable: () => LocalizedString
		/**
		 * Skúsiť znova
		 */
		retry: () => LocalizedString
		/**
		 * Aktualizovať
		 */
		buttonUpdate: () => LocalizedString
		/**
		 * Neskôr
		 */
		buttonLater: () => LocalizedString
		/**
		 * Automaticky kontrolovať pri štarte
		 */
		autoCheckOnStart: () => LocalizedString
	}
}

export type Formatters = {}
